name: Talk to Digital Ocean

on:
  push


jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Talk to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/qinyu/Hello_CICD
            sudo kill -9 $(sudo lsof -t -i:3000)
            yarn install
            yarn start

            
